name: snyk-analysis-python 
on:
  workflow_dispatch:
  push:
    paths: [requirements.txt]
jobs:     
  snyk-analysis:
    uses: awshole/snyk-node/.github/workflows/snyk-analysis.yml@main
    with:
      path_to_dependency_file: package.json
    secrets: inherit
