name: snyk-analysis-python 
on:
  workflow_dispatch:
  push:
    paths: [package.json]
jobs:     
  snyk-analysis:
    uses: awshole/snyk-node/.github/workflows/snyk-analysis.yaml@main
    with:
      path_to_dependency_file: package.json
    secrets: inherit
